version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=contacts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
